### ISSUE TITLE
Some suggestions for the UI

### ISSUE THREAD

**Issue by sigboe** [joel16/SwitchIdent#3]
I am sorry for hating on the Ubuntu theme for the GUI , I am okay with the Icon, the font, and even the layout like Gnome, but the colors are not in good taste (IMO). I would try to replicate the system menu theme for your application.
For the console the layout is okay, but the colors are awful. Please, pick anyone you like better here [github/Mayccoll/Gogh](https://github.com/Mayccoll/Gogh) (pro tip, pick one of those who has a #00000 background already).For the layout, I would much prefer if you got inspired in the style of [github.com/dylanaraps/neofetch](https://github.com/dylanaraps/neofetch)

**Comment by joel16** [comment]
Perhaps I can make improvements on the console as I can see why some of the info may be hard to read due to the colour choices used, but GUI is staying as is. I'm happy with the colours on GUI, and I've gotten lots of commendations for it. Seems more like a personal preference for you, and I surely can't impress everyone so that's staying.

Console version will likely see some improvements in the colour choices used in the future.
